const statuses=[["unknown","⬜","Pas encore"],["seen","👀","Vue"],["progress","🔄","En progression"],["known","✅","Connue"],["mastered","⭐","Maîtrisée"]];
let progress=JSON.parse(localStorage.getItem("botadexProgressV4")||localStorage.getItem("botadexProgressV3")||"{}");let notes=JSON.parse(localStorage.getItem("botadexNotesV4")||"{}");let surveys=JSON.parse(localStorage.getItem("botadexSurveysV4")||"[]");let db=null,deferredPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.onclick=()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
function openDB(){return new Promise((res,rej)=>{let r=indexedDB.open("botadexPhotosV4",1);r.onupgradeneeded=e=>e.target.result.createObjectStore("photos");r.onsuccess=e=>{db=e.target.result;res(db)};r.onerror=rej})}
function putPhoto(k,d){return new Promise(res=>{let tx=db.transaction("photos","readwrite");tx.objectStore("photos").put(d,k);tx.oncomplete=res})}
function getPhoto(k){return new Promise(res=>{let tx=db.transaction("photos","readonly");let r=tx.objectStore("photos").get(k);r.onsuccess=()=>res(r.result||"")})}
function resize(file){return new Promise(resolve=>{let img=new Image(),rd=new FileReader();rd.onload=e=>{img.onload=()=>{let c=document.createElement("canvas"),max=1000,sc=Math.min(1,max/Math.max(img.width,img.height));c.width=img.width*sc;c.height=img.height*sc;c.getContext("2d").drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",0.78))};img.src=e.target.result};rd.readAsDataURL(file)})}
function save(){localStorage.setItem("botadexProgressV4",JSON.stringify(progress));localStorage.setItem("botadexNotesV4",JSON.stringify(notes));localStorage.setItem("botadexSurveysV4",JSON.stringify(surveys))}
function getStatus(id){return progress[id]?.status||"unknown"}function setStatus(id,s){progress[id]=progress[id]||{};progress[id].status=s;save();render()}function em(id){return statuses.find(x=>x[0]===getStatus(id))?.[1]||"⬜"}function lvl(n){if(n>=1000)return"Expert flore Anjou";if(n>=700)return"Très solide terrain";if(n>=450)return"Chargée d’étude junior";if(n>=250)return"Botaniste terrain";if(n>=100)return"Naturaliste";return"Débutante botanique"}
function renderStats(){total.textContent=PLANTS.length;seen.textContent=PLANTS.filter(p=>["seen","progress","known","mastered"].includes(getStatus(p.id))).length;progressing.textContent=PLANTS.filter(p=>getStatus(p.id)==="progress").length;known.textContent=PLANTS.filter(p=>["known","mastered"].includes(getStatus(p.id))).length;mastered.textContent=PLANTS.filter(p=>getStatus(p.id)==="mastered").length;let k=PLANTS.filter(p=>["known","mastered"].includes(getStatus(p.id))).length,pct=Math.round(k/1000*100);progressBar.style.width=pct+"%";levelName.textContent=lvl(k);progressText.textContent=`${k} / 1000 plantes connues (${pct} %)`}function populateFamilies(){let cur=familyFilter.value,fam=[...new Set(PLANTS.map(p=>p.family))].sort();familyFilter.innerHTML='<option value="">Toutes familles</option>'+fam.map(f=>`<option value="${f}">${f}</option>`).join("");familyFilter.value=cur}
function renderList(){let q=search.value.toLowerCase(),fam=familyFilter.value,stat=statusFilter.value;let list=PLANTS.filter(p=>{let text=`${p.fr} ${p.latin} ${p.family} ${p.habitat} ${p.tags.join(" ")} ${p.phytosociology} ${p.eunis}`.toLowerCase();return(!q||text.includes(q))&&(!fam||p.family===fam)&&(!stat||getStatus(p.id)===stat)});plantList.innerHTML=list.map(p=>`<article class="plant ${p.special||''}"><div class="plant-head"><div class="plant-check">${em(p.id)}</div><div><h3>${p.id}. ${p.fr}</h3><div class="latin">${p.latin}</div></div></div><div class="badges"><span class="badge">${p.family}</span>${p.special==='protected'?'<span class="badge prot">protégée/patrimoniale</span>':''}${p.special==='invasive'?'<span class="badge inv">invasive</span>':''}${p.tags.slice(0,3).map(t=>`<span class="badge">${t}</span>`).join("")}</div><p>${p.short}</p><p class="phyto-mini"><b>Phyto :</b> ${p.phytosociology}</p><div class="status-row">${statuses.map(([s,e,l])=>`<button title="${l}" class="${getStatus(p.id)===s?'selected':''}" onclick="setStatus(${p.id},'${s}')">${e}</button>`).join("")}</div><button class="detail" onclick="openPlant(${p.id})">Voir plus / photos / commentaire</button></article>`).join("")}
async function openPlant(id){let p=PLANTS.find(x=>x.id===id);let ph=[];for(let i=1;i<=6;i++)ph.push(await getPhoto(`p${id}-${i}`));dialogContent.innerHTML=`<h2>${p.fr}</h2><p class="latin">${p.latin}</p><p><b>Famille :</b> ${p.family}</p><p><b>Ton statut :</b> ${em(p.id)} ${statuses.find(x=>x[0]===getStatus(p.id))?.[2]}</p><div class="photo-grid">${ph.map((x,i)=>`<div class="photo-box"><b>Photo ${i+1}</b><br>${x?`<img src="${x}">`:"<p>Aucune photo</p>"}<input type="file" accept="image/*" capture="environment" onchange="savePlantPhoto(${id},${i+1},this.files[0])"></div>`).join("")}</div><hr><p><b>Critères :</b> ${p.criteria}</p><p><b>Confusions :</b> ${p.confusions}</p><p><b>Milieu :</b> ${p.habitat}</p><p><b>Phytosociologie :</b> ${p.phytosociology}</p><p><b>EUNIS :</b> ${p.eunis}</p><p><b>Statut :</b> ${p.status}</p><label><b>Commentaires personnels :</b></label><textarea class="comment" oninput="saveNote(${id},this.value)">${notes[id]||""}</textarea>`;plantDialog.showModal()}
async function savePlantPhoto(id,n,file){if(!file)return;let data=await resize(file);await putPhoto(`p${id}-${n}`,data);openPlant(id)}function saveNote(id,v){notes[id]=v;save()}window.openPlant=openPlant;window.setStatus=setStatus;window.savePlantPhoto=savePlantPhoto;window.saveNote=saveNote;
function render(){renderStats();renderList()}document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});[search,familyFilter,statusFilter].forEach(e=>e.oninput=renderList);closeDialog.onclick=()=>plantDialog.close();
runKey.onclick=()=>{let scores={};function add(f,n){scores[f]=(scores[f]||0)+n} if(k_cap.checked)add("Asteraceae",5); if(k_cross.checked)add("Brassicaceae",5); if(k_pea.checked)add("Fabaceae",5); if(k_umbel.checked)add("Apiaceae",5); if(k_bilab.checked||k_square.checked&&k_opp.checked)add("Lamiaceae",5); if(k_gram.checked)add("Poaceae",3),add("Cyperaceae",3),add("Juncaceae",3); if(k_tri.checked)add("Cyperaceae",6); if(k_latex.checked)add("Asteraceae",2),add("Euphorbiaceae",4); if(k_comp.checked&&k_5pet.checked)add("Rosaceae",3); if(k_spines.checked)add("Rosaceae",3),add("Fabaceae",2); if(k_woody.checked)add("Rosaceae",2),add("Salicaceae",2),add("Fagaceae",1),add("Betulaceae",1); if(k_fern.checked)add("Dryopteridaceae",3),add("Aspleniaceae",3),add("Equisetaceae",3); if(k_wet.checked)add("Cyperaceae",2),add("Juncaceae",2),add("Lythraceae",1); let arr=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,8);keyResult.innerHTML=arr.length?"<h3>Familles probables</h3>"+arr.map(([f,s])=>`<p><b>${f}</b> — score ${s}<br><small>${PLANTS.filter(p=>p.family===f).slice(0,10).map(p=>p.fr).join(", ")}</small></p>`).join(""):"<p>Coche quelques critères observables.</p>"}
function doQuiz(){quizFeedback.textContent="";let p=PLANTS[Math.floor(Math.random()*PLANTS.length)],m=["family","latin","phyto"][Math.floor(Math.random()*3)],correct,question,pool;if(m==="family"){question=`Quelle est la famille de : ${p.fr} ?`;correct=p.family;pool=PLANTS.map(x=>x.family)}else if(m==="latin"){question=`Quel est le nom latin de : ${p.fr} ?`;correct=p.latin;pool=PLANTS.map(x=>x.latin)}else{question=`Repère phytosociologique probable pour : ${p.fr} ?`;correct=p.phytosociology;pool=PLANTS.map(x=>x.phytosociology)}let options=[...new Set([correct,...pool.sort(()=>Math.random()-.5).slice(0,8)])].slice(0,4).sort(()=>Math.random()-.5);quizQuestion.textContent=question;quizOptions.innerHTML=options.map(o=>`<button>${o}</button>`).join("");quizOptions.querySelectorAll("button").forEach(b=>b.onclick=()=>{if(b.textContent===correct){b.classList.add("good");quizFeedback.textContent="✅ Oui !"}else{b.classList.add("bad");quizFeedback.textContent=`❌ Réponse : ${correct}`}})}newQuiz.onclick=doQuiz;
const gloss=["Limbe : partie élargie de la feuille.","Stipule : petit appendice à la base du pétiole.","Ovaire supère : ovaire situé au-dessus du point d’insertion des pièces florales.","Ovaire infère : ovaire inclus sous les pièces florales.","Capitule : inflorescence typique des Asteraceae.","Ligule : petite languette à la jonction gaine/limbe chez les Poaceae.","Utricule : enveloppe du fruit chez les Carex.","Ochréa : gaine membraneuse aux nœuds chez beaucoup de Polygonaceae.","Hasté : en forme de fer de lance avec lobes basaux divergents.","Réniforme : en forme de rein."];
glossaryList.innerHTML=gloss.map(x=>`<p>${x}</p>`).join("");
const habs=["E1 pelouses sèches : végétation basse sur sols secs.","E2 prairies mésophiles : prairies ni très sèches ni très humides.","E3 prairies humides : prairies liées à une nappe ou engorgement.","D5 roselières/cariçaies : grandes hélophytes, roseaux, laîches.","F3 fourrés : végétation arbustive.","FA haies : linéaires arbustifs/arborés.","G1 forêts feuillues : boisements caducifoliés.","C1 eaux stagnantes : mares, étangs.","C2 eaux courantes : rivières, ruisseaux.","I1 cultures : champs et adventices."];
habitatList.innerHTML=habs.map(x=>`<p>${x}</p>`).join("");
function renderSurveys(){surveyList.innerHTML=surveys.map((s,i)=>`<div class="box"><b>${s.title}</b><p>${s.text.replaceAll("\\n","<br>")}</p><button onclick="surveys.splice(${i},1);save();renderSurveys()">Supprimer</button></div>`).join("")}saveSurvey.onclick=()=>{surveys.push({title:surveyTitle.value||"Relevé sans titre",text:surveyText.value,date:new Date().toISOString()});surveyTitle.value="";surveyText.value="";save();renderSurveys()};renderSurveys();
exportBtn.onclick=()=>exportBox.value=JSON.stringify({progress,notes,surveys});importBtn.onclick=()=>{try{let o=JSON.parse(exportBox.value||"{}");progress=o.progress||{};notes=o.notes||{};surveys=o.surveys||[];save();render();renderSurveys();alert("Importé")}catch(e){alert("Sauvegarde invalide")}};
openDB().then(()=>{populateFamilies();render()});