const statuses=[["unknown","⬜","Pas encore"],["seen","👀","Vue"],["progress","🔄","En progression"],["known","✅","Connue"],["mastered","⭐","Maîtrisée"]];
let progress=JSON.parse(localStorage.getItem("botadexProgressV3")||localStorage.getItem("botadexProgressV2")||"{}");let db=null,deferredPrompt=null;
window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;installBtn.hidden=false});installBtn.onclick=()=>{if(deferredPrompt){deferredPrompt.prompt();deferredPrompt=null}};
function openDB(){return new Promise((resolve,reject)=>{let r=indexedDB.open("botadexPhotos",1);r.onupgradeneeded=e=>e.target.result.createObjectStore("photos");r.onsuccess=e=>{db=e.target.result;resolve(db)};r.onerror=reject})}
function putPhoto(key,data){return new Promise(res=>{let tx=db.transaction("photos","readwrite");tx.objectStore("photos").put(data,key);tx.oncomplete=res})}
function getPhoto(key){return new Promise(res=>{let tx=db.transaction("photos","readonly");let r=tx.objectStore("photos").get(key);r.onsuccess=()=>res(r.result||"")})}
function resize(file){return new Promise(resolve=>{let img=new Image(),rd=new FileReader();rd.onload=e=>{img.onload=()=>{let c=document.createElement("canvas"),max=900,sc=Math.min(1,max/Math.max(img.width,img.height));c.width=img.width*sc;c.height=img.height*sc;c.getContext("2d").drawImage(img,0,0,c.width,c.height);resolve(c.toDataURL("image/jpeg",0.78))};img.src=e.target.result};rd.readAsDataURL(file)})}
function save(){localStorage.setItem("botadexProgressV3",JSON.stringify(progress))}function getStatus(id){return progress[id]?.status||"unknown"}function setStatus(id,s){progress[id]=progress[id]||{};progress[id].status=s;save();render()}function em(id){return statuses.find(x=>x[0]===getStatus(id))?.[1]||"⬜"}function lvl(n){if(n>=700)return"Expert flore Anjou";if(n>=600)return"Très solide terrain";if(n>=450)return"Chargée d’étude junior";if(n>=250)return"Botaniste terrain";if(n>=100)return"Naturaliste";return"Débutante botanique"}
function renderStats(){total.textContent=PLANTS.length;seen.textContent=PLANTS.filter(p=>["seen","progress","known","mastered"].includes(getStatus(p.id))).length;progressing.textContent=PLANTS.filter(p=>getStatus(p.id)==="progress").length;known.textContent=PLANTS.filter(p=>["known","mastered"].includes(getStatus(p.id))).length;mastered.textContent=PLANTS.filter(p=>getStatus(p.id)==="mastered").length;let k=PLANTS.filter(p=>["known","mastered"].includes(getStatus(p.id))).length,pct=Math.round(k/700*100);progressBar.style.width=pct+"%";levelName.textContent=lvl(k);progressText.textContent=`${k} / 700 plantes connues (${pct} %)`}function populateFamilies(){let cur=familyFilter.value,fam=[...new Set(PLANTS.map(p=>p.family))].sort();familyFilter.innerHTML='<option value="">Toutes familles</option>'+fam.map(f=>`<option value="${f}">${f}</option>`).join("");familyFilter.value=cur}
function renderList(){let q=search.value.toLowerCase(),fam=familyFilter.value,stat=statusFilter.value;let list=PLANTS.filter(p=>{let text=`${p.fr} ${p.latin} ${p.family} ${p.habitat} ${p.tags.join(" ")} ${p.phytosociology} ${p.eunis}`.toLowerCase();return(!q||text.includes(q))&&(!fam||p.family===fam)&&(!stat||getStatus(p.id)===stat)});plantList.innerHTML=list.map(p=>`<article class="plant"><div class="plant-head"><div class="plant-check">${em(p.id)}</div><div><h3>${p.id}. ${p.fr}</h3><div class="latin">${p.latin}</div></div></div><div class="badges"><span class="badge">${p.family}</span><span class="badge">${p.level}</span>${p.tags.slice(0,3).map(t=>`<span class="badge">${t}</span>`).join("")}</div><p>${p.short}</p><p class="phyto-mini"><b>Phyto :</b> ${p.phytosociology}</p><div class="status-row">${statuses.map(([s,e,l])=>`<button title="${l}" class="${getStatus(p.id)===s?'selected':''}" onclick="setStatus(${p.id},'${s}')">${e}</button>`).join("")}</div><button class="detail" onclick="openPlant(${p.id})">Voir plus / photos</button></article>`).join("")}
async function openPlant(id){let p=PLANTS.find(x=>x.id===id),ph1=await getPhoto(`p${id}-1`),ph2=await getPhoto(`p${id}-2`);dialogContent.innerHTML=`<h2>${p.fr}</h2><p class="latin">${p.latin}</p><p><b>Famille :</b> ${p.family}</p><p><b>Ton statut :</b> ${em(p.id)} ${statuses.find(x=>x[0]===getStatus(p.id))?.[2]}</p><div class="photo-row"><div class="photo-box"><b>Photo 1</b><br>${ph1?`<img src="${ph1}">`:"<p>Aucune photo</p>"}<input type="file" accept="image/*" capture="environment" onchange="savePlantPhoto(${id},1,this.files[0])"></div><div class="photo-box"><b>Photo 2</b><br>${ph2?`<img src="${ph2}">`:"<p>Aucune photo</p>"}<input type="file" accept="image/*" capture="environment" onchange="savePlantPhoto(${id},2,this.files[0])"></div></div><hr><p><b>Critères rapides :</b> ${p.short}</p><p><b>Critères détaillés :</b> ${p.criteria}</p><p><b>Confusions :</b> ${p.confusions}</p><p><b>Milieu :</b> ${p.habitat}</p><p><b>Phytosociologie :</b> ${p.phytosociology}</p><p><b>EUNIS :</b> ${p.eunis}</p><p><b>Indication écologique :</b> ${p.indicator}</p><p><b>Floraison :</b> ${p.phenology}</p><p><b>Statut :</b> ${p.status}</p>`;plantDialog.showModal()}
async function savePlantPhoto(id,n,file){if(!file)return;let data=await resize(file);await putPhoto(`p${id}-${n}`,data);openPlant(id)}window.openPlant=openPlant;window.setStatus=setStatus;window.savePlantPhoto=savePlantPhoto;
function render(){renderStats();renderList()}document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>{document.querySelectorAll(".tab,.panel").forEach(x=>x.classList.remove("active"));b.classList.add("active");document.getElementById(b.dataset.tab).classList.add("active")});[search,familyFilter,statusFilter].forEach(e=>e.oninput=renderList);closeDialog.onclick=()=>plantDialog.close();
idPhoto.onchange=async()=>{let f=idPhoto.files[0];if(f){idPreview.src=await resize(f);idPreview.hidden=false}};
runKey.onclick=()=>{let scores={};function add(f,n){scores[f]=(scores[f]||0)+n} if(k_square.checked&&k_opposite.checked)add("Lamiaceae",4); if(k_composite.checked)add("Asteraceae",5); if(k_cross.checked)add("Brassicaceae",5); if(k_pea.checked)add("Fabaceae",5); if(k_umbel.checked)add("Apiaceae",5); if(k_grass.checked)add("Poaceae",4); if(k_tri.checked)add("Cyperaceae",5); if(k_latex.checked)add("Asteraceae",2),add("Euphorbiaceae",3); if(k_woody.checked)add("Rosaceae",2),add("Fagaceae",1),add("Salicaceae",1); if(k_spines.checked)add("Rosaceae",3),add("Fabaceae",2); if(k_wet.checked)add("Cyperaceae",2),add("Juncaceae",2),add("Poaceae",1),add("Lamiaceae",1); let arr=Object.entries(scores).sort((a,b)=>b[1]-a[1]).slice(0,5); if(!arr.length){keyResult.innerHTML="<p>Ajoute quelques critères pour proposer une famille.</p>";return} keyResult.innerHTML="<h3>Familles probables</h3>"+arr.map(([f,s])=>`<p><b>${f}</b> — score ${s}<br><small>${PLANTS.filter(p=>p.family===f).slice(0,8).map(p=>p.fr).join(", ")}</small></p>`).join("")+"<p><b>Conseil :</b> confirme toujours avec la fleur, le fruit et une flore.</p>"};
function doQuiz(){quizFeedback.textContent="";let p=PLANTS[Math.floor(Math.random()*PLANTS.length)],m=["family","latin","phyto"][Math.floor(Math.random()*3)],correct,question,pool;if(m==="family"){question=`Quelle est la famille de : ${p.fr} ?`;correct=p.family;pool=PLANTS.map(x=>x.family)}else if(m==="latin"){question=`Quel est le nom latin de : ${p.fr} ?`;correct=p.latin;pool=PLANTS.map(x=>x.latin)}else{question=`Repère phytosociologique probable pour : ${p.fr} ?`;correct=p.phytosociology;pool=PLANTS.map(x=>x.phytosociology)}let options=[...new Set([correct,...pool.sort(()=>Math.random()-.5).slice(0,7)])].slice(0,4).sort(()=>Math.random()-.5);quizQuestion.textContent=question;quizOptions.innerHTML=options.map(o=>`<button>${o}</button>`).join("");quizOptions.querySelectorAll("button").forEach(b=>b.onclick=()=>{if(b.textContent===correct){b.classList.add("good");quizFeedback.textContent="✅ Oui !"}else{b.classList.add("bad");quizFeedback.textContent=`❌ Réponse : ${correct}`}})}newQuiz.onclick=doQuiz;exportBtn.onclick=()=>exportBox.value=JSON.stringify(progress);importBtn.onclick=()=>{try{progress=JSON.parse(exportBox.value||"{}");save();render();alert("Progression importée")}catch(e){alert("Sauvegarde invalide")}};
openDB().then(()=>{populateFamilies();render()});