const PLANTS = [
  {
    "id": 1,
    "fr": "Pissenlit",
    "latin": "Taraxacum officinale agg.",
    "family": "Asteraceae",
    "habitat": "Prairies, pelouses, bords de chemins",
    "level": "Débutant",
    "tags": [
      "commun",
      "prairie"
    ],
    "criteria": "Capitules jaunes, rosette basale, latex blanc, akènes à aigrette.",
    "confusions": "Porcelle, crépis, laiterons.",
    "status": "Non protégée",
    "short": "Capitules jaunes, rosette basale, latex blanc, akènes à aigrette.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 2,
    "fr": "Pâquerette",
    "latin": "Bellis perennis",
    "family": "Asteraceae",
    "habitat": "Pelouses, prairies pâturées",
    "level": "Débutant",
    "tags": [
      "commun",
      "prairie"
    ],
    "criteria": "Petits capitules blancs/rosés, rosette basale, fleurit presque toute l'année.",
    "confusions": "Petites marguerites.",
    "status": "Non protégée",
    "short": "Petits capitules blancs/rosés, rosette basale, fleurit presque toute l'année.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 3,
    "fr": "Trèfle blanc",
    "latin": "Trifolium repens",
    "family": "Fabaceae",
    "habitat": "Pelouses, prairies, bords de chemins",
    "level": "Débutant",
    "tags": [
      "commun",
      "fabacée"
    ],
    "criteria": "Rampant, folioles souvent marquées de clair, fleurs blanches en tête.",
    "confusions": "Autres trèfles blancs/rosés.",
    "status": "Non protégée",
    "short": "Rampant, folioles souvent marquées de clair, fleurs blanches en tête.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 4,
    "fr": "Trèfle des prés",
    "latin": "Trifolium pratense",
    "family": "Fabaceae",
    "habitat": "Prairies, talus, friches",
    "level": "Débutant",
    "tags": [
      "commun",
      "fabacée"
    ],
    "criteria": "Fleurs roses en tête dense, folioles ovales souvent avec tache claire.",
    "confusions": "Autres trèfles roses.",
    "status": "Non protégée",
    "short": "Fleurs roses en tête dense, folioles ovales souvent avec tache claire.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 5,
    "fr": "Plantain lancéolé",
    "latin": "Plantago lanceolata",
    "family": "Plantaginaceae",
    "habitat": "Prairies, pelouses, chemins",
    "level": "Débutant",
    "tags": [
      "commun"
    ],
    "criteria": "Feuilles étroites à nervures parallèles, épi brun au bout d'une hampe.",
    "confusions": "Plantain moyen.",
    "status": "Non protégée",
    "short": "Feuilles étroites à nervures parallèles, épi brun au bout d'une hampe.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 6,
    "fr": "Plantain majeur",
    "latin": "Plantago major",
    "family": "Plantaginaceae",
    "habitat": "Sols tassés, chemins, cours",
    "level": "Débutant",
    "tags": [
      "commun"
    ],
    "criteria": "Feuilles larges en rosette, nervures arquées, longs épis verdâtres.",
    "confusions": "Plantain intermédiaire.",
    "status": "Non protégée",
    "short": "Feuilles larges en rosette, nervures arquées, longs épis verdâtres.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 7,
    "fr": "Ortie dioïque",
    "latin": "Urtica dioica",
    "family": "Urticaceae",
    "habitat": "Sols riches, haies, friches, bords de fossés",
    "level": "Débutant",
    "tags": [
      "nitrophile"
    ],
    "criteria": "Plante piquante, feuilles opposées dentées, tige carrée à angles marqués.",
    "confusions": "Lamier blanc, non piquant.",
    "status": "Non protégée",
    "short": "Plante piquante, feuilles opposées dentées, tige carrée à angles marqués.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 8,
    "fr": "Liseron des champs",
    "latin": "Convolvulus arvensis",
    "family": "Convolvulaceae",
    "habitat": "Cultures, friches, jardins",
    "level": "Débutant",
    "tags": [
      "commun"
    ],
    "criteria": "Tiges volubiles, petites fleurs en entonnoir blanches/rosées, feuilles sagittées.",
    "confusions": "Calystegia sepium, plus grand.",
    "status": "Non protégée",
    "short": "Tiges volubiles, petites fleurs en entonnoir blanches/rosées, feuilles sagittées.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 9,
    "fr": "Renoncule rampante",
    "latin": "Ranunculus repens",
    "family": "Ranunculaceae",
    "habitat": "Prairies fraîches, fossés, sols humides",
    "level": "Débutant",
    "tags": [
      "humide"
    ],
    "criteria": "Fleurs jaunes brillantes, stolons rampants, feuilles en 3 lobes marqués.",
    "confusions": "Renoncule âcre, bulbeuse.",
    "status": "Non protégée",
    "short": "Fleurs jaunes brillantes, stolons rampants, feuilles en 3 lobes marqués.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 10,
    "fr": "Achillée millefeuille",
    "latin": "Achillea millefolium",
    "family": "Asteraceae",
    "habitat": "Prairies sèches, talus, bords de routes",
    "level": "Débutant",
    "tags": [
      "prairie sèche"
    ],
    "criteria": "Feuilles très finement découpées, inflorescence blanche en corymbe.",
    "confusions": "Ombellifères blanches, mais feuilles différentes.",
    "status": "Non protégée",
    "short": "Feuilles très finement découpées, inflorescence blanche en corymbe.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 11,
    "fr": "Ronce commune",
    "latin": "Rubus fruticosus agg.",
    "family": "Rosaceae",
    "habitat": "Haies, friches, lisières",
    "level": "Débutant",
    "tags": [
      "haie",
      "épineux"
    ],
    "criteria": "Tiges arquées avec aiguillons, feuilles composées, mûres noires.",
    "confusions": "Nombreuses espèces de Rubus.",
    "status": "Non protégée",
    "short": "Tiges arquées avec aiguillons, feuilles composées, mûres noires.",
    "phytosociology": "Crataego monogynae-Prunetea spinosae / Querco-Fagetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 12,
    "fr": "Églantier",
    "latin": "Rosa canina agg.",
    "family": "Rosaceae",
    "habitat": "Haies, lisières, friches",
    "level": "Débutant",
    "tags": [
      "haie",
      "épineux"
    ],
    "criteria": "Arbuste à aiguillons, fleurs roses pâles, cynorrhodons rouges.",
    "confusions": "Autres rosiers sauvages.",
    "status": "Non protégée",
    "short": "Arbuste à aiguillons, fleurs roses pâles, cynorrhodons rouges.",
    "phytosociology": "Crataego monogynae-Prunetea spinosae / Querco-Fagetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 13,
    "fr": "Aubépine monogyne",
    "latin": "Crataegus monogyna",
    "family": "Rosaceae",
    "habitat": "Haies, bocage, lisières",
    "level": "Débutant",
    "tags": [
      "haie",
      "épineux"
    ],
    "criteria": "Arbuste épineux, feuilles lobées, fleurs blanches, fruits rouges, souvent 1 style.",
    "confusions": "Aubépine à deux styles, prunellier.",
    "status": "Non protégée",
    "short": "Arbuste épineux, feuilles lobées, fleurs blanches, fruits rouges, souvent 1 style.",
    "phytosociology": "Crataego monogynae-Prunetea spinosae / Querco-Fagetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 14,
    "fr": "Prunellier",
    "latin": "Prunus spinosa",
    "family": "Rosaceae",
    "habitat": "Haies, fourrés, lisières",
    "level": "Débutant",
    "tags": [
      "haie",
      "épineux"
    ],
    "criteria": "Très épineux, fleurs blanches avant les feuilles, prunelles bleutées.",
    "confusions": "Aubépine, pruniers sauvages.",
    "status": "Non protégée",
    "short": "Très épineux, fleurs blanches avant les feuilles, prunelles bleutées.",
    "phytosociology": "Crataego monogynae-Prunetea spinosae / Querco-Fagetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 15,
    "fr": "Fraisier sauvage",
    "latin": "Fragaria vesca",
    "family": "Rosaceae",
    "habitat": "Lisières, talus, bois clairs",
    "level": "Débutant",
    "tags": [
      "bois"
    ],
    "criteria": "Feuilles trifoliées dentées, fleurs blanches, petits fruits rouges parfumés.",
    "confusions": "Potentilles.",
    "status": "Non protégée",
    "short": "Feuilles trifoliées dentées, fleurs blanches, petits fruits rouges parfumés.",
    "phytosociology": "Crataego monogynae-Prunetea spinosae / Querco-Fagetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 16,
    "fr": "Genêt à balais",
    "latin": "Cytisus scoparius",
    "family": "Fabaceae",
    "habitat": "Landes, talus acides, friches",
    "level": "Débutant",
    "tags": [
      "acide",
      "fabacée"
    ],
    "criteria": "Tiges vertes anguleuses, fleurs jaunes papilionacées, généralement non épineux.",
    "confusions": "Ajonc, genêts voisins.",
    "status": "Non protégée",
    "short": "Tiges vertes anguleuses, fleurs jaunes papilionacées, généralement non épineux.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 17,
    "fr": "Ajonc d'Europe",
    "latin": "Ulex europaeus",
    "family": "Fabaceae",
    "habitat": "Landes acides, talus, fourrés",
    "level": "Débutant",
    "tags": [
      "acide",
      "épineux",
      "fabacée"
    ],
    "criteria": "Arbuste très épineux, feuilles transformées en épines, fleurs jaunes.",
    "confusions": "Genêt à balais, mais ajonc pique fort.",
    "status": "Non protégée",
    "short": "Arbuste très épineux, feuilles transformées en épines, fleurs jaunes.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 18,
    "fr": "Lotier corniculé",
    "latin": "Lotus corniculatus",
    "family": "Fabaceae",
    "habitat": "Prairies, pelouses, talus",
    "level": "Intermédiaire",
    "tags": [
      "prairie",
      "fabacée"
    ],
    "criteria": "Fleurs jaunes parfois orangées, feuilles à 5 folioles apparentes, gousses en cornes.",
    "confusions": "Lotiers proches.",
    "status": "Non protégée",
    "short": "Fleurs jaunes parfois orangées, feuilles à 5 folioles apparentes, gousses en cornes.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 19,
    "fr": "Vesce commune",
    "latin": "Vicia sativa",
    "family": "Fabaceae",
    "habitat": "Friches, prairies, cultures",
    "level": "Intermédiaire",
    "tags": [
      "fabacée"
    ],
    "criteria": "Feuilles composées terminées par vrille, fleurs violettes/roses, gousses.",
    "confusions": "Autres vesces.",
    "status": "Non protégée",
    "short": "Feuilles composées terminées par vrille, fleurs violettes/roses, gousses.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 20,
    "fr": "Luzerne cultivée",
    "latin": "Medicago sativa",
    "family": "Fabaceae",
    "habitat": "Prairies semées, bords de champs",
    "level": "Débutant",
    "tags": [
      "fabacée"
    ],
    "criteria": "Fleurs violettes, feuilles trifoliées, port dressé.",
    "confusions": "Trèfles et luzernes proches.",
    "status": "Non protégée",
    "short": "Fleurs violettes, feuilles trifoliées, port dressé.",
    "phytosociology": "Molinio-Arrhenatheretea / Cytisetea scopario-striati selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 21,
    "fr": "Séneçon jacobée",
    "latin": "Jacobaea vulgaris",
    "family": "Asteraceae",
    "habitat": "Prairies, friches, bords de routes",
    "level": "Intermédiaire",
    "tags": [
      "prairie"
    ],
    "criteria": "Capitules jaunes, feuilles très découpées, plante toxique pour bétail.",
    "confusions": "Autres séneçons.",
    "status": "Non protégée",
    "short": "Capitules jaunes, feuilles très découpées, plante toxique pour bétail.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 22,
    "fr": "Chardon des champs",
    "latin": "Cirsium arvense",
    "family": "Asteraceae",
    "habitat": "Cultures, friches, prairies riches",
    "level": "Intermédiaire",
    "tags": [
      "épineux"
    ],
    "criteria": "Feuilles épineuses, capitules lilas, plante souvent en colonies.",
    "confusions": "Autres chardons et cirses.",
    "status": "Non protégée",
    "short": "Feuilles épineuses, capitules lilas, plante souvent en colonies.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 23,
    "fr": "Laiteron maraîcher",
    "latin": "Sonchus oleraceus",
    "family": "Asteraceae",
    "habitat": "Friches, jardins, cultures",
    "level": "Intermédiaire",
    "tags": [
      "commun"
    ],
    "criteria": "Capitules jaunes, feuilles molles embrassantes, latex blanc.",
    "confusions": "Pissenlit, crépis, laiteron rude.",
    "status": "Non protégée",
    "short": "Capitules jaunes, feuilles molles embrassantes, latex blanc.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 24,
    "fr": "Marguerite commune",
    "latin": "Leucanthemum vulgare",
    "family": "Asteraceae",
    "habitat": "Prairies, talus, bords de routes",
    "level": "Débutant",
    "tags": [
      "prairie"
    ],
    "criteria": "Grand capitule blanc à centre jaune, feuilles simples dentées.",
    "confusions": "Camomilles, matricaire, anthémis.",
    "status": "Non protégée",
    "short": "Grand capitule blanc à centre jaune, feuilles simples dentées.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 25,
    "fr": "Porcelle enracinée",
    "latin": "Hypochaeris radicata",
    "family": "Asteraceae",
    "habitat": "Pelouses, prairies maigres, sols acides",
    "level": "Intermédiaire",
    "tags": [
      "prairie maigre"
    ],
    "criteria": "Rosette de feuilles poilues, capitules jaunes sur hampes ramifiées.",
    "confusions": "Pissenlit, crépis.",
    "status": "Non protégée",
    "short": "Rosette de feuilles poilues, capitules jaunes sur hampes ramifiées.",
    "phytosociology": "Molinio-Arrhenatheretea / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 26,
    "fr": "Capselle bourse-à-pasteur",
    "latin": "Capsella bursa-pastoris",
    "family": "Brassicaceae",
    "habitat": "Cultures, jardins, chemins",
    "level": "Débutant",
    "tags": [
      "commun"
    ],
    "criteria": "Petites fleurs blanches, fruits en forme de cœur/triangle.",
    "confusions": "Autres petites Brassicaceae.",
    "status": "Non protégée",
    "short": "Petites fleurs blanches, fruits en forme de cœur/triangle.",
    "phytosociology": "Stellarietea mediae / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 27,
    "fr": "Alliaire officinale",
    "latin": "Alliaria petiolata",
    "family": "Brassicaceae",
    "habitat": "Haies, lisières, sols frais riches",
    "level": "Débutant",
    "tags": [
      "bois",
      "nitrophile"
    ],
    "criteria": "Feuilles à odeur d'ail froissées, fleurs blanches à 4 pétales.",
    "confusions": "Jeunes lamiers sans odeur d'ail.",
    "status": "Non protégée",
    "short": "Feuilles à odeur d'ail froissées, fleurs blanches à 4 pétales.",
    "phytosociology": "Stellarietea mediae / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 28,
    "fr": "Moutarde des champs",
    "latin": "Sinapis arvensis",
    "family": "Brassicaceae",
    "habitat": "Cultures, friches, bords de champs",
    "level": "Intermédiaire",
    "tags": [
      "culture"
    ],
    "criteria": "Fleurs jaunes à 4 pétales, siliques, feuilles rudes.",
    "confusions": "Ravenelle, colza échappé.",
    "status": "Non protégée",
    "short": "Fleurs jaunes à 4 pétales, siliques, feuilles rudes.",
    "phytosociology": "Stellarietea mediae / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 29,
    "fr": "Ravenelle",
    "latin": "Raphanus raphanistrum",
    "family": "Brassicaceae",
    "habitat": "Cultures, friches, sols perturbés",
    "level": "Intermédiaire",
    "tags": [
      "culture"
    ],
    "criteria": "Fleurs jaunes pâles à veinures, fruits étranglés en articles.",
    "confusions": "Moutarde des champs.",
    "status": "Non protégée",
    "short": "Fleurs jaunes pâles à veinures, fruits étranglés en articles.",
    "phytosociology": "Stellarietea mediae / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 30,
    "fr": "Cardamine des prés",
    "latin": "Cardamine pratensis",
    "family": "Brassicaceae",
    "habitat": "Prairies humides, fossés",
    "level": "Débutant",
    "tags": [
      "humide"
    ],
    "criteria": "Fleurs lilas pâle à 4 pétales, feuilles composées, milieu humide.",
    "confusions": "Autres cardamines.",
    "status": "Non protégée",
    "short": "Fleurs lilas pâle à 4 pétales, feuilles composées, milieu humide.",
    "phytosociology": "Stellarietea mediae / Artemisietea vulgaris selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 31,
    "fr": "Chêne pédonculé",
    "latin": "Quercus robur",
    "family": "Fagaceae",
    "habitat": "Bois, haies, bocage, sols frais",
    "level": "Débutant",
    "tags": [
      "arbre"
    ],
    "criteria": "Glands sur long pédoncule, feuilles à court pétiole avec oreillettes basales.",
    "confusions": "Chêne sessile.",
    "status": "Non protégée",
    "short": "Glands sur long pédoncule, feuilles à court pétiole avec oreillettes basales.",
    "phytosociology": "Querco-Fagetea",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 32,
    "fr": "Frêne élevé",
    "latin": "Fraxinus excelsior",
    "family": "Oleaceae",
    "habitat": "Haies, bois frais, bords de cours d'eau",
    "level": "Débutant",
    "tags": [
      "arbre",
      "frais"
    ],
    "criteria": "Feuilles opposées composées, bourgeons noirs, samares en grappes.",
    "confusions": "Sureau, érable negundo.",
    "status": "Non protégée",
    "short": "Feuilles opposées composées, bourgeons noirs, samares en grappes.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 33,
    "fr": "Érable champêtre",
    "latin": "Acer campestre",
    "family": "Sapindaceae",
    "habitat": "Haies, lisières, bois clairs",
    "level": "Débutant",
    "tags": [
      "arbre",
      "haie"
    ],
    "criteria": "Feuilles opposées à lobes arrondis, samares opposées presque horizontales.",
    "confusions": "Autres érables.",
    "status": "Non protégée",
    "short": "Feuilles opposées à lobes arrondis, samares opposées presque horizontales.",
    "phytosociology": "À compléter",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 34,
    "fr": "Saule blanc",
    "latin": "Salix alba",
    "family": "Salicaceae",
    "habitat": "Bords de rivières, zones humides",
    "level": "Intermédiaire",
    "tags": [
      "arbre",
      "humide"
    ],
    "criteria": "Feuilles étroites argentées dessous, arbre de ripisylve.",
    "confusions": "Autres saules.",
    "status": "Non protégée",
    "short": "Feuilles étroites argentées dessous, arbre de ripisylve.",
    "phytosociology": "Salicetea purpureae / Alnetea glutinosae",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 35,
    "fr": "Peuplier noir",
    "latin": "Populus nigra",
    "family": "Salicaceae",
    "habitat": "Vallées alluviales, bords de rivières",
    "level": "Intermédiaire",
    "tags": [
      "arbre",
      "humide"
    ],
    "criteria": "Feuilles triangulaires, long pétiole, port souvent élancé.",
    "confusions": "Peupliers hybrides.",
    "status": "Non protégée",
    "short": "Feuilles triangulaires, long pétiole, port souvent élancé.",
    "phytosociology": "Salicetea purpureae / Alnetea glutinosae",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 36,
    "fr": "Bouleau verruqueux",
    "latin": "Betula pendula",
    "family": "Betulaceae",
    "habitat": "Bois clairs, landes, sols acides",
    "level": "Débutant",
    "tags": [
      "arbre",
      "acide"
    ],
    "criteria": "Écorce blanche, rameaux pendants, feuilles triangulaires dentées.",
    "confusions": "Bouleau pubescent.",
    "status": "Non protégée",
    "short": "Écorce blanche, rameaux pendants, feuilles triangulaires dentées.",
    "phytosociology": "Querco-Fagetea / Alnetea glutinosae selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 37,
    "fr": "Châtaignier",
    "latin": "Castanea sativa",
    "family": "Fagaceae",
    "habitat": "Bois sur sols acides, bocage",
    "level": "Débutant",
    "tags": [
      "arbre",
      "acide"
    ],
    "criteria": "Grandes feuilles dentées, bogues épineuses, chatons mâles odorants.",
    "confusions": "Jeunes chênes parfois.",
    "status": "Non protégée",
    "short": "Grandes feuilles dentées, bogues épineuses, chatons mâles odorants.",
    "phytosociology": "Querco-Fagetea",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 38,
    "fr": "Noisetier",
    "latin": "Corylus avellana",
    "family": "Betulaceae",
    "habitat": "Haies, lisières, bois frais",
    "level": "Débutant",
    "tags": [
      "arbuste",
      "haie"
    ],
    "criteria": "Feuilles rondes cordées, chatons mâles pendants, noisettes.",
    "confusions": "Tilleul jeune, orme jeune.",
    "status": "Non protégée",
    "short": "Feuilles rondes cordées, chatons mâles pendants, noisettes.",
    "phytosociology": "Querco-Fagetea / Alnetea glutinosae selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 39,
    "fr": "Roseau commun",
    "latin": "Phragmites australis",
    "family": "Poaceae",
    "habitat": "Roselières, fossés, marais",
    "level": "Débutant",
    "tags": [
      "graminée",
      "humide"
    ],
    "criteria": "Très grande graminée, panicule plumeuse, tiges robustes en roselière.",
    "confusions": "Baldingère, canne de Provence.",
    "status": "Non protégée",
    "short": "Très grande graminée, panicule plumeuse, tiges robustes en roselière.",
    "phytosociology": "Molinio-Arrhenatheretea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 40,
    "fr": "Massette à larges feuilles",
    "latin": "Typha latifolia",
    "family": "Typhaceae",
    "habitat": "Mares, fossés, roselières",
    "level": "Débutant",
    "tags": [
      "humide"
    ],
    "criteria": "Épi brun cylindrique compact, feuilles larges en ruban.",
    "confusions": "Typha angustifolia, feuilles plus étroites et épis séparés.",
    "status": "Non protégée",
    "short": "Épi brun cylindrique compact, feuilles larges en ruban.",
    "phytosociology": "Phragmito australis-Magnocaricetea elatae",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 41,
    "fr": "Iris des marais",
    "latin": "Iris pseudacorus",
    "family": "Iridaceae",
    "habitat": "Bords d'eau, fossés, marais",
    "level": "Débutant",
    "tags": [
      "humide"
    ],
    "criteria": "Grandes fleurs jaunes, feuilles en glaive, bord des eaux.",
    "confusions": "Iris horticoles échappés.",
    "status": "Non protégée",
    "short": "Grandes fleurs jaunes, feuilles en glaive, bord des eaux.",
    "phytosociology": "Phragmito australis-Magnocaricetea elatae",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 42,
    "fr": "Salicaire commune",
    "latin": "Lythrum salicaria",
    "family": "Lythraceae",
    "habitat": "Berges, fossés, mégaphorbiaies",
    "level": "Débutant",
    "tags": [
      "humide"
    ],
    "criteria": "Grands épis de fleurs pourpres, feuilles opposées/verticillées.",
    "confusions": "Épilobes.",
    "status": "Non protégée",
    "short": "Grands épis de fleurs pourpres, feuilles opposées/verticillées.",
    "phytosociology": "Filipendulo ulmariae-Convolvuletea sepium",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 43,
    "fr": "Reine-des-prés",
    "latin": "Filipendula ulmaria",
    "family": "Rosaceae",
    "habitat": "Prairies humides, mégaphorbiaies, fossés",
    "level": "Débutant",
    "tags": [
      "humide"
    ],
    "criteria": "Inflorescences blanc crème odorantes, feuilles composées, odeur d'amande/médicament.",
    "confusions": "Spirée, berce jeune.",
    "status": "Non protégée",
    "short": "Inflorescences blanc crème odorantes, feuilles composées, odeur d'amande/médicament.",
    "phytosociology": "Crataego monogynae-Prunetea spinosae / Querco-Fagetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 44,
    "fr": "Menthe aquatique",
    "latin": "Mentha aquatica",
    "family": "Lamiaceae",
    "habitat": "Fossés, berges, prairies humides",
    "level": "Intermédiaire",
    "tags": [
      "humide",
      "lamiacée"
    ],
    "criteria": "Odeur de menthe, tige carrée, fleurs rosées en tête terminale.",
    "confusions": "Autres menthes.",
    "status": "Non protégée",
    "short": "Odeur de menthe, tige carrée, fleurs rosées en tête terminale.",
    "phytosociology": "Galio-Urticetea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 45,
    "fr": "Jonc diffus",
    "latin": "Juncus effusus",
    "family": "Juncaceae",
    "habitat": "Prairies humides, fossés, sols tassés humides",
    "level": "Intermédiaire",
    "tags": [
      "jonc",
      "humide"
    ],
    "criteria": "Touffes denses, tiges cylindriques lisses, inflorescence latérale apparente.",
    "confusions": "Autres joncs.",
    "status": "Non protégée",
    "short": "Touffes denses, tiges cylindriques lisses, inflorescence latérale apparente.",
    "phytosociology": "Molinio-Arrhenatheretea / Juncetea bufonii selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 46,
    "fr": "Dactyle aggloméré",
    "latin": "Dactylis glomerata",
    "family": "Poaceae",
    "habitat": "Prairies, bords de chemins, friches",
    "level": "Intermédiaire",
    "tags": [
      "graminée"
    ],
    "criteria": "Inflorescence en paquets denses, feuilles larges, gaine aplatie.",
    "confusions": "Autres graminées prairiales.",
    "status": "Non protégée",
    "short": "Inflorescence en paquets denses, feuilles larges, gaine aplatie.",
    "phytosociology": "Molinio-Arrhenatheretea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 47,
    "fr": "Ivraie vivace",
    "latin": "Lolium perenne",
    "family": "Poaceae",
    "habitat": "Prairies, pelouses, chemins",
    "level": "Intermédiaire",
    "tags": [
      "graminée"
    ],
    "criteria": "Épis alternes appliqués contre l'axe, feuilles brillantes dessous.",
    "confusions": "Chiendent, autres Lolium.",
    "status": "Non protégée",
    "short": "Épis alternes appliqués contre l'axe, feuilles brillantes dessous.",
    "phytosociology": "Molinio-Arrhenatheretea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 48,
    "fr": "Flouve odorante",
    "latin": "Anthoxanthum odoratum",
    "family": "Poaceae",
    "habitat": "Prairies maigres, pelouses, landes",
    "level": "Intermédiaire",
    "tags": [
      "graminée",
      "prairie maigre"
    ],
    "criteria": "Petite graminée précoce, odeur de foin/coumarine en séchant.",
    "confusions": "Autres petites poacées.",
    "status": "Non protégée",
    "short": "Petite graminée précoce, odeur de foin/coumarine en séchant.",
    "phytosociology": "Molinio-Arrhenatheretea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 49,
    "fr": "Fétuque élevée",
    "latin": "Schedonorus arundinaceus",
    "family": "Poaceae",
    "habitat": "Prairies, fossés, sols frais",
    "level": "Intermédiaire",
    "tags": [
      "graminée"
    ],
    "criteria": "Grande graminée robuste, feuilles larges rugueuses, ligule courte.",
    "confusions": "Dactyle, autres fétuques.",
    "status": "Non protégée",
    "short": "Grande graminée robuste, feuilles larges rugueuses, ligule courte.",
    "phytosociology": "Molinio-Arrhenatheretea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  },
  {
    "id": 50,
    "fr": "Pâturin annuel",
    "latin": "Poa annua",
    "family": "Poaceae",
    "habitat": "Chemins, trottoirs, cultures, pelouses",
    "level": "Intermédiaire",
    "tags": [
      "graminée",
      "commun"
    ],
    "criteria": "Petite graminée très commune, panicule lâche, floraison presque annuelle.",
    "confusions": "Autres Poa.",
    "status": "Non protégée",
    "short": "Petite graminée très commune, panicule lâche, floraison presque annuelle.",
    "phytosociology": "Molinio-Arrhenatheretea / Phragmito-Magnocaricetea selon contexte",
    "eunis": "À compléter",
    "phenology": "À compléter",
    "indicator": "À préciser",
    "photo": ""
  }
];